### ISSUE TITLE
Backing it up creates an infinite backup

### ISSUE THREAD

**Issue by tiotrom** [YunoHost-Apps/invidious_ynh#17]
**Describe the bug**
Try to create a backup of Invidious. It creates an infinite backup basically. Creating the directory "lib" so many times that my last backup was at around 1.2TB. Yes 1 point 2 terabytes. Took me a while to find the culprit. Granted, I used the Archivist YNH app to do the backup, but that simply triggers the YNH default backups. I am pinging the dev of Archivist too, to check this issue. Mind you, Archivist works perfectly fine with any application we tried so far (around 20+).

**Versions**
- YunoHost version: 4.1.7.3
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*

I am not sure what exact logs to provide, but probably any of you can test it.

**Comment by TROMsite** [comment]
Just an update. The reason it failed is because there are many symlink folders linking to the parent folder and it goes into an infinite loop. As we discussed here https://github.com/YunoHost-Apps/archivist_ynh/issues/35 

So basically inside the folder www/invidious/lib pretty much every folder has a "lib" folder symlink that links back to the parent folder and so on.

Are tehse symlinks necessary?

**Comment by TROMsite** [comment]
Just so you know this is still an issue....cannot update invidious at all. Need to delete it and reinstall to update it....

**Comment by tio-trom** [comment]
Is there a way to fix this? I think this is a critical bug which makes it impossible to backup or upgrade invidious. I have to purge it and reinstall every time there is an update. Thanks!

**Comment by tio-trom** [comment]
More info about this....since I really want to make it work. These are the commends that are triggered by Archivist:

Command:
`/usr/bin/python3 /usr/bin/yunohost backup create --apps invidious --methods copy --output-directory /home/yunohost.app/archivist/backup/ynh_backup/temp --name invidious_backup.temp`

Parent process 	`sudo BACKUP_CORE_ONLY=0 yunoho .`

Command 	`sudo BACKUP_CORE_ONLY=0 yunohost backup create --apps invidious --methods copy --output-directory /home/yunohost.app/archivist/backup/ynh_backup/temp --name invidious_backup.temp`

Command 	`/bin/bash /opt/yunohost/archivist/archivist.sh`

It creates an infinite loop in invidious lib/db. And it is endless. It is weird because works fine to create a manual backup via the ynh admin panel. Why is that?
