### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by snm247** [YunoHost-Apps/invidious_ynh#19]
**Describe the bug**
The installation of Invidious for YunoHost failed. 

**Versions**
- Hardware: amd64 computer at home
- YunoHost version: 4.1.7.4
- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: master

**To Reproduce**

```sh
sudo yunohost app install https://github.com/YunoHost-Apps/invidious_ynh
```

**Expected behavior**
The installation is successful.

**Logs**
https://paste.yunohost.org/raw/ajadofebim

From the logs:

```sh
Unable to satisfy the following requirements:
2021-03-29 17:53:49,028: DEBUG - 
2021-03-29 17:53:49,028: DEBUG - - `crystal (>= 0.35.0, < 2.0.0)` required by `pg 0.23.2`
2021-03-29 17:53:49,028: DEBUG - - `crystal (>= 0.35.0, < 2.0.0)` required by `sqlite3 0.18.0`
2021-03-29 17:53:49,028: DEBUG - - `crystal (~> 0.35, >= 0.35.0)` required by `kemal 0.27.0`
2021-03-29 17:53:49,028: DEBUG - - `crystal (< 1.0.0)` required by `pool 0.2.3`
2021-03-29 17:53:49,029: DEBUG - - `crystal (~> 0.34, >= 0.34.0)` required by `protodec 0.1.3`
2021-03-29 17:53:49,029: DEBUG - - `crystal (~> 0.35, >= 0.35.1)` required by `lsquic 2.18.1-1`
2021-03-29 17:53:49,029: DEBUG - - `crystal (>= 0.35.0, < 2.0.0)` required by `db 0.10.1`
2021-03-29 17:53:49,029: DEBUG - - `crystal (< 1.0.0)` required by `radix 0.3.9`
```

Maybe the problem is that there was a new crystal 1.0.0 release a few days ago so the requirement `< 1.0.0` is not met anymore?

**Comment by ericgaspar** [comment]
I made a fix in the testing branch, it now downloads Crystal 0.36 and not Crystal 1.0.0. Tell me if it fixes the issue.
`sudo yunohost app install https://github.com/YunoHost-Apps/invidious_ynh/tree/testing`

**Comment by snm247** [comment]
The installation is still failing, but the logs look different:  
https://paste.yunohost.org/raw/tununobapo

**Comment by lentemoore** [comment]
Installation also fails for me, here are the logs: https://paste.yunohost.org/raw/solotizeja

**Comment by ericgaspar** [comment]
@lentemoore From you logs, you are installing version `0.20.1~ynh6`. The version in master is `0.20.1~ynh8`This version may not yet be available througt web admin install. You can try to install it with CLI : `sudo yunohost app install https://github.com/YunoHost-Apps/invidious_ynh`

**Comment by razzor1984** [comment]
@ericgaspar  - Still Fails on crystal 

Tested HW: Rpi 3B+

sudo yunohost app install https://github.com/YunoHost-Apps/invidious_ynh

Info: Installing invidious...
Info: [....................] > Validating installation parameters...
Info: [+...................] > Storing installation settings...
Info: [#...................] > Finding an available port...
Info: [#++++...............] > Installing dependencies...
Warning: gpg: key 379CE192D401AB61: public key "Bintray (by JFrog) <bintray@bintray.com>" imported
Warning: gpg: Total number processed: 1
Warning: gpg:               imported: 1
Warning: E: Unable to locate package crystal
Error: Unable to install invidious: An error occurred inside the app installation script
Info: The operation 'Install the 'invidious' app' could not be completed. Please share the full log of this operation using the command 'yunohost log display 20210416-144303-app_install-invidious --share' to get help
Warning: Here's an extract of the logs before the crash. It might help debugging the error:
Info: DEBUG - + eval curl -fsSL https://crystal-lang.org/install.sh
Info: DEBUG - ++ curl -fsSL https://crystal-lang.org/install.sh
Info: DEBUG - + bash -s -- --crystal=0.36
Info: DEBUG - Warning: apt-key output should not be parsed (stdout is not a terminal)
Info: INFO - [#++++...............] > Installing dependencies...
Info: DEBUG - Executing: /tmp/apt-key-gpghome.I2GBzPab9G/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
Info: WARNING - gpg: key 379CE192D401AB61: public key "Bintray (by JFrog) <bintray@bintray.com>" imported
Info: WARNING - gpg: Total number processed: 1
Info: WARNING - gpg:               imported: 1
Info: DEBUG - deb https://dl.bintray.com/crystal/deb all stable
Info: DEBUG - Ign:1 https://dl.bintray.com/crystal/deb all InRelease
Info: DEBUG - Get:2 https://dl.bintray.com/crystal/deb all Release [3,611 B]
Info: DEBUG - Get:4 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Info: DEBUG - Get:5 http://archive.raspberrypi.org/debian buster InRelease [32.9 kB]
Info: DEBUG - Hit:6 http://forge.yunohost.org/debian buster InRelease
Info: DEBUG - Fetched 51.5 kB in 9s (6,048 B/s)
Info: DEBUG - Reading package lists...
Info: DEBUG - Reading package lists...
Info: DEBUG - Building dependency tree...
Info: DEBUG - Reading state information...
Info: DEBUG - + ynh_exit_properly
Warning: Removing the app following the installation failure...
Info: [+...................] > Loading installation settings...
Info: [#+..................] > Stopping and removing the systemd service...
Info: [##++................] > Removing the PostgreSQL database...
Warning: cat: /etc/yunohost/psql: No such file or directory
Warning: sudo: unknown user: postgres
Warning: sudo: unable to initialize policy plugin
Warning: Database  not found
Warning: cat: /etc/yunohost/psql: No such file or directory
Warning: sudo: unknown user: postgres
Warning: sudo: unable to initialize policy plugin
Warning: User  not found
Info: [####+...............] > Removing dependencies...
Warning: E: Unable to locate package invidious-ynh-deps
Info: '/etc/apt/sources.list.d/invidious.list' wasn't deleted because it doesn't exist.
Info: '/etc/apt/preferences.d/invidious' wasn't deleted because it doesn't exist.
Info: '/etc/apt/trusted.gpg.d/invidious.gpg' wasn't deleted because it doesn't exist.
Info: '/etc/apt/trusted.gpg.d/invidious.asc' wasn't deleted because it doesn't exist.
Warning: ynh_secure_remove called with empty argument, ignoring.
Info: [#####++++++.........] > Removing Invidious main directory...
Info: [###########+++++....] > Removing NGINX web server configuration...
Info: '/etc/nginx/conf.d/yunhostinvidious.home.d/invidious.conf' wasn't deleted because it doesn't exist.
Info: [################+...] > Removing logrotate configuration...
Info: '/etc/cron.d/invidious' wasn't deleted because it doesn't exist.
Warning: The user invidious was not found
Info: [#################+..] > Removing the dedicated system user...
Error: The operation 'Install the 'invidious' app' could not be completed. Please share the full log of this operation using the command 'yunohost log display 20210416-144303-app_install-invidious --share' to get help

**Comment by AlexioSisko** [comment]
Installation failed to me today: https://paste.yunohost.org/raw/soqogutapa

**Comment by TROMsite** [comment]
Installation fails again, with yet another error:
`2021-05-14 04:22:33,906: WARNING - E: Version '0.36*' for 'crystal' was not found`

**Comment by SpcCw** [comment]
Currently I get the following:

```
Unable to satisfy the following requirements:

- `crystal (>= 0.35.0, < 2.0.0)` required by `pg 0.23.2`
- `crystal (>= 0.35.0, < 2.0.0)` required by `sqlite3 0.18.0`
- `crystal (~> 0.35, >= 0.35.0)` required by `kemal 0.27.0`
- `crystal (*)` required by `pool 0.2.4`
- `crystal (~> 0.34, >= 0.34.0)` required by `protodec 0.1.3`
- `crystal (~> 0.35, >= 0.35.1)` required by `lsquic 2.18.1-1`
- `crystal (>= 0.35.0, < 2.0.0)` required by `db 0.10.1`
- `crystal (< 1.0.0)` required by `radix 0.3.9`
```
Crystal version is: crystal/unknown,now 1.0.0-1+61.1 amd64

**Comment by ericgaspar** [comment]
Sooo ... I made another attempt to install Crystal from the GitHub repository. Can anyone test from the test branch ... 
`sudo yunohost app install https://github.com/YunoHost-Apps/invidious_ynh/tree/testing`

**Comment by snm247** [comment]
At first try my YunoHost server ran out of memory. After adding a swap file and trying again:

```
Success! Installation completed
```

So finally Invidious is working on my YunoHost server.  
Thanks a lot for the fix!

**Comment by razzor1984** [comment]
Hello @snm247 it only works if the aritecture is x86 and supports 64bit:
i tried it on an rasbperry pi 3+/arm and crystal ist killing it.....
2021-06-05 13:56:10,601: DEBUG - dpkg: error processing archive /tmp/tmp.vnTabYOnOG/crystal_0.36.1-1_amd64.deb (--install):
2021-06-05 13:56:10,601: DEBUG -  package architecture (amd64) does not match system (armhf)

**Comment by jhammons** [comment]
Thank you!
